project_id = "sjydlxpogzbaxgbufwnp"

[functions.shopify-import-orders]
verify_jwt = true

[functions.shopify-bulk-import]
verify_jwt = true

[functions.shopify-webhook]
verify_jwt = false

[functions.order-webhook]
verify_jwt = false

[functions.setup-shopify-webhooks]
verify_jwt = true

[functions.clear-orders]
verify_jwt = true
